language: c

sudo: required

before_install:
  - echo "yes" | sudo add-apt-repository ppa:avsm/ppa
  - sudo apt update
  - sudo apt install opam
  - export OPAMYES=1      # answer all questions of opam with 'y'
  #- export OPAMVERBOSE=1
  - opam init
  - opam install -v alba

script: bash -ex script.sh

env:
  - ENVIRONMENT_1=1

os:
  - linux
